### ISSUE TITLE
can seem to install the app

### ISSUE THREAD

**Issue by hidus** [Frixs/BlackSpiritHelper#42]
i have .NET Framework 4.7.2 installed and antivirus (windows defender turned off) and i am running the setup as admin. still getting this:
added the certificate too.
ERROR DETAILS
	Following errors were detected during this operation.
	* [31-01-2021 2.52.48 AM] System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore(UInt32 Flags, IntPtr hToken, Guid& riid)
			at System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore()
			at System.Deployment.Application.ComponentStore..ctor(ComponentStoreType storeType, SubscriptionStore subStore)
			at System.Deployment.Application.SubscriptionStore..ctor(String deployPath, String tempPath, ComponentStoreType storeType)
			at System.Deployment.Application.SubscriptionStore.get_CurrentUser()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

please help.
thanks

**Comment by hidus** [comment]
found the solution for this:
had to create a new windows user for my pc. then go to this file and delete it from my newly created account C:\Users\user\AppData\Local\Microsoft\Windows\UsrClass.dat
then installation started.
